name: Publish Tag

on:
  push:
    tags:
      - 1.*.*

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.24.0
      
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.11.1
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false
      
      - name: Disallow installation scripts
        run: yq '.onlyBuiltDependencies = []' -i pnpm-workspace.yaml
      
      - name: Install deps
        run: pnpm install --frozen-lockfile
      
      - name: Publish
        run: npm i -g npm@^11.5.2 && pnpm run ci-publish "$REF_NAME"
        env:
          REF_NAME: ${{ github.ref_name }}
